version: '3'

services:
    go-test-app:
        build: .
        ports:
            - '3000:8001'
        # docker environment variable
        environment:               
            - GO_PORT=8001
            - MONGOURI=mongodb://mongo:27017

    mongo:
        image: "mongo"
        ports:
            - '27017:27017'
        volumes:
            - "mongodb:/data/db"

    redis:
        image: "redis:alpine"
        ports:
            - '6379:6379'
        
    
volumes:
    mongodb:
        driver: local
        # command: bash -c "nodemon server.js"
